version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - 6002:80
    networks:
      - backend
      - frontend

  php:
    build:
      context: ./php
    container_name: php
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 6001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - backend
    #links:
    #  - 'mysql:mydatabase'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mysql:




# TEST1
# services:
#   nginx:
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile
#     container_name: nginx
#     restart: unless-stopped
#     ports:
#       - 6666:80
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./dist:/usr/share/nginx/html
#     depends_on:
#       - PHP
#       - mysql
#       - phpmyadmin
#     networks:
#       - backend
#       - frontend
  
#   PHP:
#     build:
#       context: ./php
#       dockerfile: Dockerfile
#     container_name: php
#     restart: unless-stopped
#     expose:
#       - 9000
#     volumes:
#       - ./php:/var/www/html
#     networks:
#       - backend
  
#   mysql:
#     image: mysql:5.7
#     container_name: mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test
#       MYSQL_USER: test
#       MYSQL_PASSWORD: test

#     expose:
#       - 3306
#     #ports:
#     #  - 3306:3306
#     volumes:
#       - ./mysql:/var/lib/mysql
#     networks:
#       - backend

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     restart: unless-stopped
#     environment:
#       PMA_HOST: mysql
#       PMA_PORT: 3306
#     ports:
#       - 6001:80
#     depends_on:
#       - mysql
#     networks:
#       - backend

# volumes:
#   mysql:
  
  
# networks:
#   backend:
#     driver: bridge
#   frontend:
#     driver: bridge
    






##GENERATED
# services:
#   nginx:
#     image: nginx:1.13.6-alpine
#     ports:
#       - 80:80
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./dist:/usr/share/nginx/html
#     depends_on:
#       - api
#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test
#       MYSQL_USER: test
#       MYSQL_PASSWORD: test
#     ports:
#       - 3306:3306
#     volumes:
#       - ./mysql:/var/lib/mysql
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: mysql
#       PMA_PORT: 3306
#     ports:
#       - 8080:80
#     depends_on:
#       - mysql
# volumes:
#   mysql:
